name: file_picker_desktop
description: A package that allows you to use a native file explorer on Windows, macOS, and Linux to pick a directory or one or multiple files, with extension filtering support.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  test: ^1.17.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
