name: file_picker_desktop
description: A package that allows you to use a native file explorer on Windows, macOS, and Linux to pick a directory or one or multiple files, with extension filtering support.
version: 1.0.0-dev.1

repository: https://github.com/philenius/flutter_file_picker_desktop
issue_tracker: https://github.com/philenius/flutter_file_picker_desktop/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
